spring:
  cloud:
    gateway:
        routes:
          - id: order-service
            uri: lb://ORDER-SERVICE # Load balancing
            predicates:
              - Path=/api/v1/**
server:
  port: 9294
