spring:
  cloud:
    gateway:
        routes:
          - id: order-service
            uri: http://localhost:8080 # TODO add load balancing
            predicates:
              - Path=/api/v1/**
server:
  port: 9294
