spring:
  cloud:
    gateway:
        routes:
        - id: order-service
          uri: lb:http://localhost:8080 # Load balancing
          predicates:
            - Path=/api/v1/**
server:
  port: 9294
